### ISSUE TITLE
How to connect "sfe movie"

### ISSUE THREAD

**Issue by JohnSoz** [Yalir/sfeMovie#102]
Tell me how to connect it http://sfemovie.yalir.org/1.0/
to my project. 
Error appears when you start:
"Could not find any video decoder for this video format"
Or is there any exception, and the program crash.
![zz0k1lojr7m](https://cloud.githubusercontent.com/assets/25349002/22298983/83688e0e-e333-11e6-816d-46f4271be6d0.jpg)

**Comment by Ceylo** [comment]
Hello JohnSoz,

Version 1.0 of sfeMovie is outdated. See http://sfemovie.yalir.org/latest/ for the latest version.

As for the error you get, it just means the decoders you need are not in the binary of sfeMovie you're using. See http://sfemovie.yalir.org/latest/faq.php#supported-codecs
You probably need to download a binary with all the decoders or build sfeMovie yourself.

**Comment by JohnSoz** [comment]
I could not build sfe movie
And so the use of "sfeMovie-1.0-windows-vs2012.zip", connecting the include
and lib to the project.
I will try to use a newer version.I just have to throw dll in the files
with the project?


25 янв. 2017 г. 21:31 пользователь "Ceylo" <notifications@github.com>
написал:

**Comment by Ceylo** [comment]
Yes sfeMovie works like any other library. See "Using sfeMovie" section in http://sfemovie.yalir.org/latest/start.php for more details.

**Comment by JohnSoz** [comment]
Errors are now no.
Video is also no :-).
Here is the code:
Movie movie;
movie.openFromFile("video.webm");
window.setFramerateLimit(60);
window.setVerticalSyncEnabled(true);

movie.fit(0, 0,100,100);
movie.play();

while (window.isOpen())
{

window.clear();
window.draw(movie);
window.display();
}
All I'm doing is correct?

2017-01-25 22:36 GMT+03:00 Ceylo <notifications@github.com>:

**Comment by feliwir** [comment]
Do you get any errors in your stdout? If this codec is not suported there should be a message. Apart from that your code looks correct, yes. But you need to make sure your codec is supported by your sfeMovie binary

**Comment by JohnSoz** [comment]
![image](https://cloud.githubusercontent.com/assets/25349002/22330128/a6f75196-e3d5-11e6-9907-f9585317e747.png)
![image](https://cloud.githubusercontent.com/assets/25349002/22330148/c962b45a-e3d5-11e6-8f33-ee3f445927e3.png)

No errors. I tried to use different video formats, but it did not produce results.

**Comment by JohnSoz** [comment]
My code was not correct!
I did so, and there was a white screen for a few seconds and then there was an error in the console.
while (window.isOpen())
{
		move.play();
		move.update();
		window.clear();
		window.draw(move);
		window.display();
}
![image](https://cloud.githubusercontent.com/assets/25349002/22330432/3eb4bbee-e3d7-11e6-9b39-5dba14d5fad3.png)

**Comment by Ceylo** [comment]
play() should not be in the loop

**Comment by Ceylo** [comment]
Apart from that if you are interested you can find a working example here: https://github.com/Yalir/sfeMovie/blob/master/examples/MinimalistDemo/main.cpp

**Comment by JohnSoz** [comment]
Thank you very much for the prompt assistance!
Now everything is working!
