### ISSUE TITLE
Huge texture update queue

### ISSUE THREAD

**Issue by SDraw** [Yalir/sfeMovie#103]
If video stream is not updated every frame or process is resumed after suspension, OpenGL command queue will be filled with huge amount of texture updating commands.
Situation is common if you use debugger (in my case, VS debugger and gDEBugger).
Maybe it is how it should be, but this situation is not good for my project.
http://i.imgur.com/xEiNz0R.png

**Comment by Ceylo** [comment]
Hello SDraw,

I understand what you mean but if you want this to change you'll need to do the fix as I'm not maintaining sfeMovie anymore.

Also, theoretically the queue should not be this big: when sfeMovie detects that the video stream is late compared to the main clock, it skips texture uploads and does only video frame decoding. Then when it has caught up it starts updating textures again.
