### ISSUE TITLE
Hello everybody, changes are coming....

### ISSUE THREAD

**Issue by crazybytes** [Yalir/sfeMovie#108]
Ok, here is the deal.

The maintainers of sfemovie, AND sfemoviefix, will have to contact the ffmpeg club.
You know, using ffmpeg-2.8 is out of date, and the sfemovie uses it, because of changes in the new ffmpeg code.
So, YOU HAVE TO WORK TOGETHER, to update the sfemovie so it adapts the ffmpeg.
Also tell the ffmpeg team, to WORK TOGETHER on this, so you sfemovie wil be fixed and updated, so it will word (in the future ALWAYS) together with the new ffmpeg codes.

For cross compiling ffmpeg they use msys2 (mingw32.exe or mingw64.exe shell), in accordance with 

MXE

Ok? But the mxe is also trapped with all kind of incompatibility shit, they put in it on purpose.
They are trolling around, you know.
So, all read this thread:

https://github.com/mxe/mxe/issues/2255

And what my team found out on mxe:

https://www.facebook.com/groups/991955800991440/ 

That is what you encounter installing mxe, witch is needed to cross compile ffmpeg with the newest shit, but its also corrupted. So i told them and gave them a ultimatum of one week. Yes, ONE WEEK.

Same goes here, you have one week to contact with the ffmpeg team, then TOGETHER fix the sfemovie and ffmpeg, 

with also the MXE team,

Get in touch with each other, the illuminati infiltrated everything, and nobody knows who is who, its a secret based society.

THEN, go to :

https://www.facebook.com/HetProgramma/

Its dutch. But go to 

https://hetprogramma.wordpress.com/

and translate the pages, AND READ IT, ALL OF YOU!

That is what they do to people who are in the open source with good intentions, but are being gang stalked until they die, or worse (...)

Ok?

Well, if things on mxe, sfemovie (with the SFML team also), ffmpeg etc.

ARE NOT FIXED,

This is what will happen to the devils, rats, and trolls who work for the illuminati (money) guys.

We will turn the page, and give them back what they gave to honest good people with good intentions.

So the illuminati rats inside the open source can stop what they are doing, otherwise they will face court, and will be broke for live.

Its an ultimatum. So, everybody join together to fix everything, because its everywhere.
Its you mother, its your father, its your brother, its your sister, its your aunt, its your uncle, etc.
(William Bill Cooper, rip).

SO, READ IT ALL, CONTACT WITH ALL PARTS OF THE OPEN SOURCE, AND FIX ALL, 

I mean all, also websites etc, because everything is corrupted, and people like me who tell so, will be declared insane and end up in isolation or on meds, with whole families destroyed.
I know you think i am nuts, because i am. But i am willing to catch the bullets for you.

SO, GET IT FIXED:
update sfemovie and/or sfemovie fix to ffmpeg4. And contact the mxe and msys2 dudes, tell them to quit following illuminati orders, because they wil be dismantled without a war or bloodshed.

FIX IT.

**Comment by Ceylo** [comment]
1. I don't have any obligation, I don't care about your ultimatum.
2. I don't maintain sfeMovie anymore, and this isn't going to change just because of your request.
3. Yes you're nuts. Don't expect me to consider you seriously in such state.
4. Whatever you want, you can alway make your own fork and handle everything yourself.
