### ISSUE TITLE
Seeking in the movie

### ISSUE THREAD

**Issue by Ceylo** [Yalir/sfeMovie#6]
TODO:

- [x] make sure seeking is done in valid range
- [x] be able to seek on a global (ie. all streams) basis to key frames
 - [x] if seeking went too late for one stream, must redo the seeking process for all streams
 - [x] flush the previously buffered data
    - [x] flush each stream encoded data
    - [x] flush the demuxer temporary data
    - [x] flush the audio driver data
 - [x] ~~set the movie position to the really reached position~~ (not needed anymore, only accurate seeking done)
 - [x] be able to notify seeking failure for broken medias
 - [x] be able to seek to non-key frames when seeking to key frames fails?
- [x] be able to seek to exact target position
 - [x] fast forward after seeking to key frame
  - [x] discard unwanted video packets
  - [x] discard unwanted audio data
    - [x] discard unwanted audio packets
    - [x] then discard unwanted audio samples
  - [x] discard unwanted subtitles
- [x] preload image at reached position to display it when playback is paused / stopped?

TOFIX:
- [x] computePosition() does not give the exact position when there is buffered data
- [x] crash on Windows when flushing the subtitles, see http://i.imgur.com/5jo4CmI.png?1
- [x] crash on OS X with OpenAL, likely that OpenAL implementation on OS X isn't thread-safe… see LaurentGomila/SFML#541
- [x] when seeking a bit before the end of some movies, video gets stuck
- [x] when stopping, seeking then stopping again, image doesn't get reset to the first image because even though seeking did its job and loaded the image at the target seek point, the movie is still stopped (so it can't be stopped again and position reset)
- [x] some medias have video streams with packets that don't contain enough data to decode a full image, although the decoding pipeline has been running for some time: this makes the video stream late

**Comment by Ceylo** [comment]
This branch has reached a usable state: video will be a few frames early and audio slightly late but apart from that and the reported bugs it looks good.

@simpsonjon @bluekirby0 @svkampen @firefly2442 @feliwir Now it would be nice if anyone could help at testing the widest possible variety of media and report for any accuracy or a new issue :) To seek just click at some position in the demo program window.

**Comment by feliwir** [comment]
I very rarely still get crashes in Demuxer.cpp line 665. (in here:  void Demuxer::didSeek)

**Comment by Ceylo** [comment]
Can you give instructions about how to reproduce it?

**Comment by feliwir** [comment]
No, it occured one time out of a houndred seeks and it didn't occur again, so i am not sure what caused/ how to reproduce it

**Comment by Ceylo** [comment]
Ok, note that you need to have SFML 2.3/Git head to have correct behavior (at least on Linux, Windows may be concerned too).

**Comment by notklaatu** [comment]
Ceylo, what branch should I use to try out the seeking feature? I built once with the internal ffmpeg and once with my own compile, and neither of them appear to allow me to seek (at least in the sample movie player). Do I just need to build my own player to try out the feature?  I am willing to do that; I'm just curious to try it. Cheers.

**Comment by feliwir** [comment]
The branch you need to checkout is 6_seeking and you should be able to use seeking in the sample player (just click along the timeline). If you want to build your own player that uses seeking just look at the sample code :)

**Comment by Ceylo** [comment]
@simpsonjon @bluekirby0 @svkampen @feliwir @notklaatu 

All the required tasks for this feature have been completed and the Movie class now has a setPlayingOffset() method. Can you take some time to test it with your preferred media files?

Here are download links of binaries with all the built-in decoders that FFmpeg support:
- Linux: http://yalir.org:8888/job/sfeMovieQuick/194/BuildType=Debug,Compiler=GCC,Decoders=All,OS=Linux/artifact/ci-output/sfeMovie-Debug-2.0.0-Linux.zip
- OS X: http://yalir.org:8888/job/sfeMovieQuick/194/BuildType=Debug,Compiler=GCC,Decoders=All,OS=OSX/artifact/ci-output/sfeMovie-Debug-2.0.0-Darwin.zip
- Windows (Visual Studio 2013): http://yalir.org:8888/job/sfeMovieQuick/194/BuildType=Debug,Compiler=MSVC12,Decoders=All,OS=Windows/artifact/ci-output/sfeMovie-Debug-2.0.0-win32.zip

Note that MinGW is not supported anymore and that you need SFML 2.3 or a build from its Git sources. Major bugfixes have been added to SFML 2.3 (whose release look to be a matter of hours or at most a few days now).

**Comment by Ceylo** [comment]
Updated builds based on now freshly released SFML 2.3:
- [Linux](http://yalir.org:8888/job/sfeMovieQuick/195/BuildType=Debug,Decoders=All,OS=Linux/artifact/ci-output/sfeMovie-Debug-2.0.0-Linux.zip)
- [OS X](http://yalir.org:8888/job/sfeMovieQuick/195/BuildType=Debug,Decoders=All,OS=OSX/artifact/ci-output/sfeMovie-Debug-2.0.0-Darwin.zip)
- [Windows (Visual Studio  2013)](http://yalir.org:8888/job/sfeMovieQuick/195/BuildType=Debug,Decoders=All,OS=Windows/artifact/ci-output/sfeMovie-Debug-2.0.0-win32.zip)

**Comment by Ceylo** [comment]
Tested on all 3 OSs on my side and saw no problem so this is going to be merged :)

**Comment by Ceylo** [comment]
Merged! Release being built

**Comment by notklaatu** [comment]
This is so cool!! Thanks!

**Comment by Ceylo** [comment]
Thank you too for your support ^^
