### ISSUE TITLE
Streams don't get selected in the same order as how they're displayed in stdout

### ISSUE THREAD

**Issue by Ceylo** [Yalir/sfeMovie#62]
Using the shortcut to display the media info can show for example:

```
5 streams found in the media
 #0 : video
 #1 : audio (language: ger)
 #2 : audio (language: eng)
 #3 : subtitle (language: eng)
 #4 : subtitle (language: ger)
```

Where the streams 0 and 1 are active.
Selecting the next audio and subtitle streams selects streams 2 and 4 instead of 2 and 3.

Quite a minor issue but can be disturbing.

**Comment by feliwir** [comment]
I was not able to reproduce this error on my linux machine:
 #0 : video
 #1 : audio (language: ger)
 #2 : audio (language: eng)
 #3 : subtitle (language: eng)
 #4 : subtitle (language: ger)
Selected subtitle stream #3 (lang: eng)
Selected audio stream #2 (lang: eng)

**Comment by Ceylo** [comment]
Could not reproduce too, closing.
