### ISSUE TITLE
Display subtitles

### ISSUE THREAD

**Issue by Ceylo** [Yalir/sfeMovie#7]
CA:
- [x] for media files that have supported bundled subtitles, I want the active subtitle stream to be displayed
- [x] Bitmap subtitles must be supported
- [x] libass-powered subtitles must be supported

Requires: #49

**Comment by feliwir** [comment]
I tested ass-subtitles and they seem to work pretty good already

**Comment by Ceylo** [comment]
This is now merged and released.
