### ISSUE TITLE
VS2013) locally defined symbol imported warnings

### ISSUE THREAD

**Issue by hsdk123** [Yalir/sfeMovie#83]
I realise that when I build my project with sfeMovie,
I get the following warnings:
```
warning LNK4049: locally defined symbol ??1Movie@sfe@@UAE@XZ (public: virtual __thiscall sfe::Movie::~Movie(void)) imported
```
I don't think I should just be disabling the warning for this one - is there anything sfeMovie could do to clear the warnings?

**Comment by feliwir** [comment]
Can you tell me which version of msvc you are using so i can reproduce this error?

**Comment by hsdk123** [comment]
@feliwir Thanks for the reply - I'm using Visual Studio 2013

**Comment by feliwir** [comment]
@hsdk123 i use visual studio 2013 aswell, but i don't get this error (when building sfeMovieSample). My guess is that you are trying to use the static lib but you forget about the SFEMOVIE_STATIC macro. Since you are using visual studio you could check how SFE_API is defined in Visibility.hpp?

**Comment by hsdk123** [comment]
@feliwir Thanks, that was exactly it :+1:
