### ISSUE TITLE
Released sfeMovie depends on debug version of SFML 

### ISSUE THREAD

**Issue by segalaj** [Yalir/sfeMovie#85]
**Problem**
Released sfeMovie depends on debug version of SFML, so it can not be embedded in a project with a released version of SFML.

**How to reproduce**
On Linux, download released version Linux 64 bits / Free decoders, in <sfeMovie>/usr/local/lib/, print shared library dependencies:
```
> ldd libsfeMovie.so
...
libsfml-graphics-d.so.2 => not found
libsfml-window-d.so.2 => not found
libsfml-system-d.so.2 => not found
libsfml-audio-d.so.2 => not found
...
```

**Comment by Ceylo** [comment]
Oh crap! I check this now. By the way I didn't know about the ldd command, thanks :)

**Comment by Ceylo** [comment]
It is weird for the available binaries to have this issue. I have the exact opposite locally: both debug and release build depends on release binaries of SFML >.>

**Comment by Ceylo** [comment]
Ok it looks like FindSFML will always use the same binaries if it can't find both, whatever the current build mode, and I only had debug version installed on the Linux builder… :D

**Comment by Ceylo** [comment]
Just rebuilt SFML from latest sources (will be needed for upcoming seeking support anyway) in both debug/release mode on the Linux slave and installed.

It's building there: https://yalir.org:8080/job/sfeMovieRelease/26/ so as soon as you see that the dots are all blue you can try to download again from the website. I'll check when I can but the build will be finished before I'm able to do so :)

**Comment by segalaj** [comment]
Seems to be fixed ! Thanks a lot.
And I'll wait for seeking support !

**Comment by Ceylo** [comment]
Great! I also checked on Windows and there are both debug and release binaries so there should be no problem :)
