### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by rvbiljouw** [Yalir/sfeMovie#90]
I can't seem to pinpoint exactly where things are going wrong, but when playing multiple videos one after another it seems that the memory allocated for each video is retained...

Maybe I'm just doing something really stupid but I've been hitting the same issue for a while now and I'm struggling to find where the problem is.

Code sample: https://gist.github.com/rvbiljouw/39cb54df0b6d63f4380d

**Comment by Ceylo** [comment]
Do you notice any different when executing within and out of any debugger? And with same file format & codec vs different file format & codec?

**Comment by rvbiljouw** [comment]
I don't see any difference between running it through a debugger (gdb) or just by itself. I only use the h.264 codec encoding in production but I'm going to see if the same thing happens when running solely off of h.262 and see if that makes a difference.

**Comment by feliwir** [comment]
Hi, can you maybe run your application via valgrind? It would tell us if the memory leak is somewhere in your code or in sfeMovie. Thanks

**Comment by rvbiljouw** [comment]
Apologies, I've been on holiday so didn't have the chance to get back to this issue..

@feliwir: I've gisted a valgrind memcheck logfile here: https://gist.github.com/rvbiljouw/1ebec7417d2e3cbe2891

Problem is still occurring, I hope we can figure out why :(

**Comment by Ceylo** [comment]
No worries, it was vacations here too :)

I checked your valgrind report and looked at the leaks reported at the end (the biggest ones). Some look to come from FFmpeg which look to allocate some buffer once and never free them. I guess these are on purpose and are only allocated once, so they would not be the culprit in your case.

At the moment I don't even know if the issue comes from FFmpeg, sfeMovie or SFML or some other dependency. About your sample code, can you provide a self-contained minimalist source program so that we're sure to reproduce the same issue?

**Comment by rvbiljouw** [comment]
Yep, I'll work on getting a sample program together this weekend. Some interesting thing that came up from experiments is that I can't seem to reproduce the memory leak (or at least not as severe) on windows, so there's a chance that the issue stems from dodgy graphics drivers (fglrx) under Linux.. Will update when I know more.

**Comment by Ceylo** [comment]
Actually thanks to http://sfemovie.yalir.org/forum/viewtopic.php?id=50 I've been able to reproduce a leak. It looks similar to your: happening after reloading new media files.

**Comment by Ceylo** [comment]
I've pushed a fix on branch bugfix/90+91_LeakOnReload
You can also find debug binaries with all decoders here:
- Linux: [sfeMovie-Debug-2.0.0-Linux.zip](http://yalir.org:8888/job/sfeMovieQuick/233/BuildType=Debug,Decoders=All,OS=Linux/artifact/ci-output/sfeMovie-Debug-2.0.0-Linux.zip)
- OS X: [sfeMovie-Debug-2.0.0-Darwin.zip](http://yalir.org:8888/job/sfeMovieQuick/233/BuildType=Debug,Decoders=All,OS=OSX/artifact/ci-output/sfeMovie-Debug-2.0.0-Darwin.zip)
- Windows (VS 2013): [sfeMovie-Debug-2.0.0-win32.zip](http://yalir.org:8888/job/sfeMovieQuick/233/BuildType=Debug,Decoders=All,OS=Windows/artifact/ci-output/sfeMovie-Debug-2.0.0-win32.zip)

Could you test for the OS you use and tell me if it's ok on your side too?

**Comment by Ceylo** [comment]
Fix has been reported to be ok on forum so I merge to master and close this issue.
